name: Trigger nightly build

on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    # we want the nightly builds only on work days
    - cron:  '0 0 * * 2-6'
  workflow_dispatch:

jobs:
  trigger-nightly:
    name: Push tag for nightly build
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.NIGHTLY_BUILD_GH_TOKEN }}
      -
        name: 'Push new tag'
        # TODO determine nightly version based on latest minor version
        run: |
          git config user.name "maha-hajja"
          git config user.email "maha.d.hajja@gmail.com"
          git pull --tags
          DESCRIBE= `git describe --match "v[0-9].[0-9].[0-9]" --abbrev=0`
          MINOR_VERSION=`echo $DESCRIBE | awk '{split($0,a,"."); print a[2]}'`
          MINOR_VERSION="$((${MINOR_VERSION} + 1))"
          TAG="v0.${MINOR_VERSION}.0-nightly.$(date +'%Y%m%d')"
          git tag -a $TAG -m "$TAG: nightly build"
          git push origin $TAG

